# Generated by Django 5.2.3 on 2025-06-23 08:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Batch ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('total_records', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Records Processed')),
                ('successful_records', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Successful Records')),
                ('failed_records', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Failed Records')),
                ('processing_status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='processing', max_length=20, verbose_name='Processing Status')),
                ('error_details', models.TextField(blank=True, null=True, verbose_name='Error Details')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uploaded By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload Histories',
                'db_table': 'upload_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoGrn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(help_text='Serial number from the uploaded file', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serial Number')),
                ('location', models.CharField(help_text='Store/warehouse location', max_length=255, verbose_name='Location')),
                ('po_number', models.CharField(db_index=True, help_text='Purchase Order Number', max_length=100, verbose_name='PO Number')),
                ('po_creation_date', models.DateField(help_text='Date when the PO was created', verbose_name='PO Creation Date')),
                ('no_item_in_po', models.IntegerField(help_text='Total number of items in the purchase order', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Items in PO')),
                ('po_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the purchase order', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='PO Amount')),
                ('po_status', models.CharField(help_text='Status of the purchase order (e.g., Completed, In Process)', max_length=50, verbose_name='PO Status')),
                ('supplier_name', models.CharField(db_index=True, help_text='Name of the supplier/vendor', max_length=255, verbose_name='Supplier Name')),
                ('concerned_person', models.CharField(blank=True, help_text='Person responsible for the PO', max_length=255, null=True, verbose_name='Concerned Person')),
                ('grn_number', models.CharField(blank=True, db_index=True, help_text='Goods Receipt Note Number', max_length=100, null=True, verbose_name='GRN Number')),
                ('grn_creation_date', models.DateField(blank=True, help_text='Date when the GRN was created', null=True, verbose_name='GRN Creation Date')),
                ('no_item_in_grn', models.IntegerField(blank=True, help_text='Total number of items in the goods receipt note', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Items in GRN')),
                ('received_status', models.CharField(blank=True, help_text='Status of goods receipt (e.g., Received, Pending)', max_length=50, null=True, verbose_name='Received Status')),
                ('grn_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal amount before tax in GRN', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GRN Subtotal')),
                ('grn_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount in GRN', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GRN Tax')),
                ('grn_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount including tax in GRN', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GRN Amount')),
                ('upload_batch_id', models.CharField(db_index=True, help_text='Unique identifier for the upload session', max_length=100, verbose_name='Upload Batch ID')),
                ('uploaded_filename', models.CharField(help_text='Original filename of the uploaded file', max_length=255, verbose_name='Uploaded Filename')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'PO GRN Record',
                'verbose_name_plural': 'PO GRN Records',
                'db_table': 'po_grn',
                'ordering': ['s_no', 'po_creation_date'],
                'indexes': [models.Index(fields=['po_number'], name='po_grn_po_numb_94133c_idx'), models.Index(fields=['grn_number'], name='po_grn_grn_num_0c8acb_idx'), models.Index(fields=['supplier_name'], name='po_grn_supplie_244948_idx'), models.Index(fields=['upload_batch_id'], name='po_grn_upload__9fa8ba_idx'), models.Index(fields=['po_creation_date'], name='po_grn_po_crea_536a64_idx'), models.Index(fields=['grn_creation_date'], name='po_grn_grn_cre_e86286_idx')],
                'unique_together': {('po_number', 'grn_number', 'upload_batch_id')},
            },
        ),
    ]
